### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by aorin1** [kirby561/DDR-USB-Dance-Pad-Driver#1]
It seems this driver can probably solve my issue since I`m using SCP driver for PS3 gamepads, the dance mat is recognized as an Xbox controller.
Do I have to build this driver using Visual Studio, can the driver be provided ready to use for Windows users?

**Comment by kirby561** [comment]
Hi aorin.  Sorry for the late response.  The current repo you must build from source to use.

Also this will not work with regular controllers.  The desktop app talks to an Arduino using serial over USB.  I connected the switches on my dance pad directly to the arduino (see instructions in the readme).  I did this because I was having reliability issues with the adapters I bought on Amazon so I just built my own.  I'd be happy to help reproduce the setup if the instructions in the readme are not good enough.

**Comment by kirby561** [comment]
Closing since no response in a few years.
